# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe535c26f9d087eed2d4ea503aa9035727ebdfa86c6c1caa1f0398f16b3bc562764f63ffdee7aa9e79739cfa127fa51238928f124e4837169090f135204cda7d

test:
  secret_key_base: 38d78932403ab57fd6b0addf02108ea1ec2080822e25b9e62dde5f66a126eeb62b2fe06328788a4f6310da7e309e420d73966765112308ee1969c632b610bb35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
